[project]
name = "plot"
version = "0.0.1"
requires-python = ">=3.9"
dependencies = [
    "numpy",
    "pandas",
    "seaborn",
    "jupyter"
]

[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = []

